INSERT INTO ARTICLE(ID, TITLE, CONTENT) VALUES(1, '개똥이의 여행','즐거운 여행');
INSERT INTO ARTICLE(ID, TITLE, CONTENT) VALUES(2, '개똥이의 여행2','즐거운 여행2');
INSERT INTO ARTICLE(ID, TITLE, CONTENT) VALUES(3, '개똥이의 여행3','즐거운 여행3');